import enum


class PositionEnum(enum.IntEnum):
    __               = 0x0
    FASEUP_ATTACK    = 0x1
    FASEDOWN_ATTACK  = 0x2
    FASEUP_DEFENCE   = 0x4
    FASEDOWN_DEFENCE = 0x8
    FACEUP = FASEUP_ATTACK | FASEUP_DEFENCE 
    FACEDOWN = FASEDOWN_ATTACK | FASEDOWN_DEFENCE
    ATTACK = FASEUP_ATTACK | FASEDOWN_ATTACK
    DEFENCE = FASEUP_DEFENCE | FASEDOWN_DEFENCE
